# Generated by Django 6.1.1 on 2026-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
