# Generated by Django 6.1.1 on 2026-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_medicaldocument_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ocr_layout',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ocr_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
