# Generated by Django 6.1.1 on 2026-09-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_medicaldocument_ocr_layout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbhaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abha_number', models.CharField(max_length=14, unique=True)),
                ('abha_address', models.CharField(blank=True, max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abha_profile', to='patients.patient')),
            ],
        ),
    ]
