# Generated by Django 6.1.1 on 2026-09-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
